### ISSUE TITLE
cannot load library: libmupdf.so

### ISSUE THREAD

**Issue by rado31** [gen2brain/go-fitz#120]
* My code

```go
package main

import (
	"image/jpeg"
	"log"
	"os"

	"github.com/gen2brain/go-fitz"
)

func main() {
	// Open the PDF document
	doc, err := fitz.New("sample.pdf")

	if err != nil {
		log.Fatal(err)
	}

	defer doc.Close()

	// Get the first page
	img, err := doc.Image(0) // Page 0 is the first page

	if err != nil {
		log.Fatal(err)
	}

	// Create the output file
	outFile, err := os.Create("output.jpg")

	if err != nil {
		log.Fatal(err)
	}

	defer outFile.Close()

	// Encode the image to a JPEG format and write it to the file
	err = jpeg.Encode(outFile, img, nil)

	if err != nil {
		log.Fatal(err)
	}
}

```

* Build command: ```GOOS=linux GOARCH=amd64 go build -o converter main.go```
* Machine: Ubuntu 24.04.1 x64
* Installed packages: ```mupdf mupdf-dev mupdf-tools libmupdf-dev```
* Tried to search with command: ```sudo find / -name libmupdf.so```. NO RESULTS
* Full error

```bash
panic: cannot load library: libmupdf.so: cannot open shared object file: No such file or directory

goroutine 1 [running]:
github.com/gen2brain/go-fitz.loadLibrary()
        C:/Users/RaDo/go/pkg/mod/github.com/gen2brain/go-fitz@v1.24.14/purego_linux.go:18 +0x73
github.com/gen2brain/go-fitz.init.0()
        C:/Users/RaDo/go/pkg/mod/github.com/gen2brain/go-fitz@v1.24.14/fitz_nocgo.go:570 +0x17
```

### There is no ```libmupdf.so``` file on the SERVER (remote machine) even after installed packages (as mentioned above)

**Comment by gen2brain** [comment]
You are using an experimental purego implementation that needs the shared mupdf library. Build with CGO_ENABLED=1.

**Comment by gen2brain** [comment]
And of course, you cannot cross-compile cgo project just like that, you need C toolchain/compiler for target platform.

**Comment by rado31** [comment]
Thanks for feedback. I've got it
