### ISSUE TITLE
panic: runtime error: gobytes: length out of range

### ISSUE THREAD

**Issue by shockerjue** [gen2brain/go-fitz#71]
`
for i := 0; i < doc.NumPage() - 1; i++ {
  img, err := doc.Image(i)
  if nil != err {
	  continue
  }
}
`

panic: runtime error: gobytes: length out of range

goroutine 163 [running]:
github.com/gen2brain/go-fitz._Cfunc_GoBytes(...)
        _cgo_gotypes.go:927
github.com/gen2brain/go-fitz.(*Document).ImageDPI.func13(0xc0009c0080?, {0x2802bcc0?, 0x7fcf?, 0x0?, 0x40855555?})
        /opt/go/pkg/mod/github.com/gen2brain/go-fitz@v1.20.2/fitz.go:226 +0x4f
github.com/gen2brain/go-fitz.(*Document).ImageDPI(0xc0009c0080, 0x0, 0x4072c00000000000)
        /opt/go/pkg/mod/github.com/gen2brain/go-fitz@v1.20.2/fitz.go:226 +0x412
github.com/gen2brain/go-fitz.(*Document).Image(...)
        /opt/go/pkg/mod/github.com/gen2brain/go-fitz@v1.20.2/fitz.go:177
crontask/reading.Reading.pdf({}, {0x17bdf97, 0x2}, {0xc000a88300, 0x56})

**Comment by rootgrandfather** [comment]
@gen2brain I also encountered the same problem and this file can reproduce this issue. [c17e66c3af24dd25debdd95387cad7b5.pdf](https://github.com/gen2brain/go-fitz/files/14221596/c17e66c3af24dd25debdd95387cad7b5.pdf)

**Comment by rootgrandfather** [comment]
Error Stack:

panic: runtime error: gobytes: length out of range [recovered]
	panic: runtime error: gobytes: length out of range

goroutine 69 [running]:
testing.tRunner.func1.2({0x7ff705368e00, 0x7ff705da0100})
	D:/Program Files/Go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	D:/Program Files/Go/src/testing/testing.go:1529 +0x39f
panic({0x7ff705368e00, 0x7ff705da0100})
	D:/Program Files/Go/src/runtime/panic.go:884 +0x213
github.com/gen2brain/go-fitz._Cfunc_GoBytes(...)
	_cgo_gotypes.go:945
github.com/gen2brain/go-fitz.(*Document).ImageDPI.func13(0x202fc4c4040?, {0xfc451350?, 0x202?, 0x0?, 0x40855555?})
	d:/GoProjects/myproj/vendor/github.com/gen2brain/go-fitz/fitz.go:257 +0x4f
github.com/gen2brain/go-fitz.(*Document).ImageDPI(0xc0004ee040, 0x0, 0x4072c00000000000)
	d:/GoProjects/myproj/vendor/github.com/gen2brain/go-fitz/fitz.go:257 +0x425
github.com/gen2brain/go-fitz.(*Document).Image(...)
	d:/GoProjects/myproj/vendor/github.com/gen2brain/go-fitz/fitz.go:207
myproj/utils/myhelper.ConvertPdfToPngs({0x7ff7055f1b77, 0x3d}, {0x7ff7055de39b, 0x29}, 0x8)
	d:/GoProjects/myproj/utils/myhelper/pdftool.go:55 +0x24e
myproj/tests.Test_ConvertPdfToPngs(0xc000485520)
	d:/GoProjects/myproj/tests/office_convertor_test.go:91 +0x8e
testing.tRunner(0xc000485520, 0x7ff705bd5420)
	D:/Program Files/Go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	D:/Program Files/Go/src/testing/testing.go:1629 +0x3ea
