### ISSUE TITLE
system crash when converting page to image

### ISSUE THREAD

**Issue by bao-huynh-ostv** [gen2brain/go-fitz#82]
Hi, im converting around 30 pages to jpg, size of each image around 500kb to 2mb. Some image was converted successfully but some throw errors

```signal 16 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime.throw({0x1052c8854?, 0x14000072000?})
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/panic.go:1047 +0x40 fp=0x140001e8e10 sp=0x140001e8de0 pc=0x10488a6f0
runtime.sigNotOnStack(0x10)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/signal_unix.go:1029 +0x5c fp=0x140001e8e30 sp=0x140001e8e10 pc=0x1048a09fc
runtime.adjustSignalStack(0x10, 0x105e4c040, 0x140001e8ed8)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/signal_unix.go:581 +0x250 fp=0x140001e8ea0 sp=0x140001e8e30 pc=0x10489fd30
runtime.sigtrampgo(0x10, 0x140001e9040, 0x140001e90a8)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/signal_unix.go:469 +0x170 fp=0x140001e8f20 sp=0x140001e8ea0 pc=0x10489f980
runtime.sigtrampgo(0x10, 0x140001e9040, 0x140001e90a8)
        <autogenerated>:1 +0x1c fp=0x140001e8f50 sp=0x140001e8f20 pc=0x1048bde5c
runtime.sigtramp()
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/sys_darwin_arm64.s:227 +0x4c fp=0x140001e9010 sp=0x140001e8f50 pc=0x1048bcccc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000084fe0 sp=0x14000084fe0 pc=0x1048bbc94

goroutine 1 [IO wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/proc.go:381 +0xe0 fp=0x1400011fa70 sp=0x1400011fa50 pc=0x10488d0c0
runtime.netpollblock(0x140002efb08?, 0x492b4f4?, 0x1?)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/netpoll.go:527 +0x158 fp=0x1400011fab0 sp=0x1400011fa70 pc=0x104886838
internal/poll.runtime_pollWait(0x12d732038, 0x72)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/netpoll.go:306 +0xa0 fp=0x1400011fae0 sp=0x1400011fab0 pc=0x1048b5b10
internal/poll.(*pollDesc).wait(0x14000193900?, 0x10486bfe0?, 0x0)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28 fp=0x1400011fb10 sp=0x1400011fae0 pc=0x104926b58
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x14000193900)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/internal/poll/fd_unix.go:614 +0x250 fp=0x1400011fbc0 sp=0x1400011fb10 pc=0x10492b5e0
net.(*netFD).accept(0x14000193900)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/net/fd_unix.go:172 +0x28 fp=0x1400011fc80 sp=0x1400011fbc0 pc=0x1049ece78
net.(*TCPListener).accept(0x1400000f9f8)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/net/tcpsock_posix.go:148 +0x28 fp=0x1400011fcb0 sp=0x1400011fc80 pc=0x104a03a68
net.(*TCPListener).AcceptTCP(0x1400000f9f8)
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/net/tcpsock.go:284 +0x2c fp=0x1400011fcf0 sp=0x1400011fcb0 pc=0x104a02afc
github.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0x140002efd48?})
        /Users/baohuynh/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/echo.go:982 +0x1c fp=0x1400011fd30 sp=0x1400011fcf0 pc=0x104f7264c
github.com/labstack/echo/v4.(*tcpKeepAliveListener).Accept(0x140000021a0?)
        <autogenerated>:1 +0x2c fp=0x1400011fd50 sp=0x1400011fd30 pc=0x104f78b6c
net/http.(*onceCloseListener).Accept(0x140001d4b40?)
        <autogenerated>:1 +0x30 fp=0x1400011fd70 sp=0x1400011fd50 pc=0x104b0f700
net/http.(*Server).Serve(0x1400030a0f0, {0x1058b10d0, 0x14000010988})
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/net/http/server.go:3059 +0x2cc fp=0x1400011fea0 sp=0x1400011fd70 pc=0x104aecdec
github.com/labstack/echo/v4.(*Echo).Start(0x14000342240, {0x1052948ec, 0x5})
        /Users/baohuynh/go/pkg/mod/github.com/labstack/echo/v4@v4.10.2/echo.go:679 +0xc0 fp=0x1400011fee0 sp=0x1400011fea0 pc=0x104f708c0
main.main()
        /Users/baohuynh/PhuocBao/Coding/otsv/one-gallery/api-one-magazine/cmd/main.go:23 +0xfc fp=0x1400011ff70 sp=0x1400011fee0 pc=0x104f7966c
runtime.main()
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/proc.go:250 +0x200 fp=0x1400011ffd0 sp=0x1400011ff70 pc=0x10488ccb0
runtime.goexit()
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400011ffd0 sp=0x1400011ffd0 pc=0x1048bbc94
```

Below is the code, i just following the snippet
![Screen Shot 2023-05-17 at 10 12 06](https://github.com/gen2brain/go-fitz/assets/83700639/5d765e39-99e2-4005-a4bd-4101e08c38c9)

I'm using arm64 arch to execute those code

**Comment by gen2brain** [comment]
I don't see any reference to `go-fitz` in your crash. What is needed is a small reproducible code with problematic documents, not some description of what you are doing. Sorry, like it is nobody can help.

**Comment by bao-huynh-ostv** [comment]
> I don't see any reference to `go-fitz` in your crash. What is needed is a small reproducible code with problematic documents, not some description of what you are doing. Sorry, like it is nobody can help.

Hi @gen2brain , sorry for my missing code, i just updated the code

**Comment by gen2brain** [comment]
Basically, does this code work or not for you, if not, the document you are using can possibly be useful:
```
package main

import (
	"fmt"
	"image/jpeg"
	"os"
	"path/filepath"

	"github.com/gen2brain/go-fitz"
)

func main() {
	doc, err := fitz.New("test.pdf")
	if err != nil {
		panic(err)
	}

	defer doc.Close()

	tmpDir, err := os.MkdirTemp(os.TempDir(), "fitz")
	if err != nil {
		panic(err)
	}

	// Extract pages as images
	for n := 0; n < doc.NumPage(); n++ {
		img, err := doc.Image(n)
		if err != nil {
			panic(err)
		}

		f, err := os.Create(filepath.Join(tmpDir, fmt.Sprintf("test%03d.jpg", n)))
		if err != nil {
			panic(err)
		}

		err = jpeg.Encode(f, img, &jpeg.Options{jpeg.DefaultQuality})
		if err != nil {
			panic(err)
		}

		f.Close()
	}
}
```

**Comment by bao-huynh-ostv** [comment]
Hi @gen2brain, i try to use those code but it still got errors related to goroutine

**Comment by gen2brain** [comment]
I cannot reproduce crash with your example file and with the code I pasted above, that same code crashes for you or what? You are mentioning goroutines, you are actually trying to use goroutines for `Image()` or not? That is like the one and only open issue and that is not supported. Please, I don't want to pull the info from you anymore, I don't have time for that, send an example that will crash. If you are trying to use goroutines then the issue is invalid, because that is not supported.

**Comment by bao-huynh-ostv** [comment]
I used the code that you sent me above, not modify anything except the path. Can you try to reproduce on apple m1 device?

**Comment by theeldarka** [comment]
2nd option works for me. Thanks ChatGPT

<img width="831" alt="image" src="https://github.com/user-attachments/assets/4fd17ff2-15be-40b5-ad26-a7db475de8fe">
<img width="825" alt="image" src="https://github.com/user-attachments/assets/b5dda65d-134f-4787-a59a-ed57f01f3638">
